// GENERATED by tools/gen_pcb.py from tools/placement.py -- do not edit.
// Board (KiCad) coordinates through bx()/byy() defined in the shell file.
sw1   = [bx(141), byy(43)];    // RESET  (top-face button hole)
sw2   = [bx(141), byy(52)];    // BOOTSEL (pinhole)
ws    = [bx(101), byy(44.5)];  // WS2812 light pipe
usb   = [bx(124), byy(30)];    // USB-C exits trailing edge
sd    = [bx(88), byy(30)];    // microSD exits trailing edge
holes = [[bx(55), byy(33)], [bx(145), byy(33)], [bx(55), byy(84)], [bx(145), byy(84)]];
ant_c = bx(68);                // ESP32 antenna centre X (overhangs trailing edge)
