// GENERATED by tools/gen_pcb.py from tools/placement.py -- do not edit.
// KiCad board frame (mm, y down): x 50..150, y 30 (top edge) .. 125.5 (tab base) .. 140 (insertion edge).
pcb_x0 = 50; pcb_x1 = 150; pcb_y0 = 30; pcb_tab_y = 125.5; pcb_y1 = 140; pcb_t = 1.2;
pcb_outline = [[50, 30], [150, 30], [150, 97.5], [145, 97.5], [145, 100], [148.5, 100], [148.5, 106], [150, 106], [150, 125.5], [146.75, 125.5], [146.75, 140], [53.25, 140], [53.25, 125.5], [50, 125.5], [50, 108.5], [51.5, 108.5], [51.5, 102.5], [55, 102.5], [55, 100], [50, 100]];
pcb_holes = [[100, 72, 5], [105.5, 62.5, 3]];   // [x, y, diameter]
sw_reset   = [143.5, 72];   // RESET (top face)
sw_bootsel = [144.5, 112];   // BOOTSEL (pinhole)
sw_s3_en   = [56.5, 62];   // ESP32-S3 EN
sw_s3_boot = [56.5, 72];   // ESP32-S3 BOOT
led_ws     = [121, 66];   // WS2812 light pipe
usb_c      = [125, 30];   // USB-C exits the top edge
microsd    = [100, 30];   // microSD exits the top edge
esp32_ant  = [66, 30];   // ESP32 antenna centre (at the top edge)
