// FujiNet-NES Rev0 cartridge shell -- a printable envelope in NES Game Pak
// proportions with the openings this board needs.  Board positions come from
// board-anchors.scad (generated by tools/gen_pcb.py).  See case-spec.md for
// the sources and the VERIFY items.  CERN-OHL-W-2.0.
//
//   openscad -D part=\"front\" -o shell-front.stl FujiNet-NES-Shell.scad
//   openscad -D part=\"back\"  -o shell-back.stl  FujiNet-NES-Shell.scad
include <board-anchors.scad>

part = "both";          // "front" (label side), "back", "both" (preview)
$fn = 48;

// ---- Game Pak envelope (VERIFY) ------------------------------------------
cart_w   = 120;         // across the fingers
cart_h   = 133;         // insertion direction
cart_t   = 19.5;        // front face to back face
wall     = 2.0;
split_t  = 7.5;         // front half thickness (label side); back half = cart_t - split_t
corner_r = 3.0;

// ---- the board inside ------------------------------------------------------
pcb_w    = pcb_x1 - pcb_x0;             // 100
pcb_body = pcb_tab_y - pcb_y0;          // 95.5
tab_d    = pcb_y1 - pcb_tab_y;          // 14.5
tab_w    = 93.5;
pcb_front_gap = 3.0;    // board top face to the inside of the front wall (tallest part 3.2 mm: USB-C)
pcb_z    = wall + pcb_front_gap + 3.3;  // board FRONT face z (measured from the shell front face)
bottom_inset = 3.0;     // the finger edge sits this far inside the shell's bottom face
slot_w   = 96;          // bottom opening for the console's connector
slot_t   = 7;

// board frame -> shell frame: shell origin at the bottom-left-front corner,
// x across, y up (insertion edge at the bottom), z toward the back
function bx(x) = (cart_w - pcb_w) / 2 + (x - pcb_x0);
function byy(y) = bottom_inset + (pcb_y1 - y);         // y=140 (edge) -> bottom_inset

module rrect(w, h, r) { offset(r) offset(-r) square([w, h]); }

module envelope() {
    linear_extrude(cart_t) rrect(cart_w, cart_h, corner_r);
}

module cavity() {
    // the board volume plus room above it on both faces
    translate([wall, wall, wall]) linear_extrude(cart_t - 2 * wall) rrect(cart_w - 2 * wall, cart_h - 2 * wall, corner_r - 1);
}

module board_cutout() {
    // the board itself (so the halves' rails leave it room) ...
    translate([0, 0, pcb_z - 0.2]) linear_extrude(pcb_t + 0.4)
        polygon([for (p = pcb_outline) [bx(p[0]), byy(p[1])]]);
    // ... and the connector slot through the bottom face
    translate([(cart_w - slot_w) / 2, -1, pcb_z - (slot_t - pcb_t) / 2]) cube([slot_w, bottom_inset + tab_d + 1, slot_t]);
}

module top_well(x, w, d, depth) {
    // a well from the top face down to the board's top edge (USB-C plug, microSD card)
    translate([bx(x) - w / 2, byy(pcb_y0) - 0.5, pcb_z - (d - pcb_t) / 2])
        cube([w, cart_h - byy(pcb_y0) + 1, d]);
}

module front_openings() {
    for (sw = [sw_reset, sw_bootsel, sw_s3_en, sw_s3_boot])
        translate([bx(sw[0]), byy(sw[1]), -1]) cylinder(d = 4.0, h = wall + 2);
    translate([bx(led_ws[0]), byy(led_ws[1]), -1]) cylinder(d = 3.0, h = wall + 2);
}

module posts() {
    // through the board's holes and beside its notches; they also register the halves
    for (h = pcb_holes)
        translate([bx(h[0]), byy(h[1]), 0]) cylinder(d = h[2] - 0.3, h = cart_t);
    for (p = [[pcb_x0 + 2.5, pcb_tab_y - 21.25], [pcb_x1 - 2.5, pcb_tab_y - 23.75]])   // in the notches
        translate([bx(p[0]), byy(p[1]), 0]) cylinder(d = 4.0, h = cart_t);
}

module shell() {
    difference() {
        union() {
            difference() { envelope(); cavity(); }
            intersection() { envelope(); posts(); }
        }
        board_cutout();
        top_well(usb_c[0], 12, 7, 0);          // USB-C plug body
        top_well(microsd[0], 14, 3.5, 0);      // microSD card
        front_openings();
        // antenna window: thin the front wall over the ESP32 antenna
        translate([bx(esp32_ant[0]) - 10, byy(pcb_y0) - 8, wall - 0.8]) cube([20, 8, 1]);
    }
}

module front_half() { intersection() { shell(); translate([-1, -1, -1]) cube([cart_w + 2, cart_h + 2, split_t + 1]); } }
module back_half()  { intersection() { shell(); translate([-1, -1, split_t]) cube([cart_w + 2, cart_h + 2, cart_t]); } }

if (part == "front") front_half();
else if (part == "back") translate([0, 0, cart_t]) mirror([0, 0, 1]) back_half();   // print face down
else { front_half(); back_half(); }
