// GENERATED by tools/gen_pcb.py from tools/placement.py -- do not edit.
// Board (KiCad) coordinates; the shell file maps them with bx()/by().
board = [72.8, 30, 127.2, 118];   // x0, y0, x1, y1 (top edge y0, insertion edge y1)
shoulder_y = 92.28;             // full board width above this y; shell stops above it
sw_reset   = [77.4, 80.2];
sw_bootsel = [96, 87.6];
sw_s3rst   = [77.4, 62.6];
sw_s3boot  = [77.4, 71.4];
ws_led     = [107.6, 50.6];   // WS2812 light pipe
rp_led     = [104.2, 57.8];   // RP activity LED
usb_x      = 120;         // USB-C exits the top edge
sd_x       = 102.2;         // microSD exits the top edge
ant        = [83.6, 36.35];   // ESP32-S3 module centre (antenna at the top edge)
holes = [[76, 55.6], [125, 51.6], [76, 88.6], [124, 88.6]];
