// GENERATED by tools/gen_pcb.py from tools/placement.py -- do not edit.
// KiCad board frame (mm, y down): body x 63.8..136.2, y 35 (top edge) .. 133.5 (tab base);
// tab x 76.5..123.5 down to the insertion edge y 150.
pcb_x0 = 63.8; pcb_x1 = 136.2; pcb_y0 = 35; pcb_tab_y = 133.5; pcb_y1 = 150; pcb_t = 1.6;
pcb_tab_x0 = 76.5; pcb_tab_x1 = 123.5;
pcb_slots = [[82.29, 84.69], [115.31, 117.71]];   // key slots [x0, x1], from the insertion edge up to pcb_slot_top
pcb_slot_top = 140;
// F.Cu (the component side, pins 1-16) faces the console REAR; B.Cu the player.
pcb_outline = [[65.8, 35], [134.2, 35], [136.2, 37], [136.2, 132.5], [135.2, 133.5], [123.5, 133.5], [123.5, 149], [122.5, 150], [117.71, 150], [117.71, 140], [115.31, 140], [115.31, 150], [84.69, 150], [84.69, 140], [82.29, 140], [82.29, 150], [77.5, 150], [76.5, 149], [76.5, 133.5], [64.8, 133.5], [63.8, 132.5], [63.8, 37]];
pcb_holes = [[67.4, 95, 3.2], [132.6, 95, 3.2], [67.4, 129.9, 3.2], [132.6, 129.9, 3.2]];   // [x, y, diameter]: the shell screws
sw_reset   = [68.6, 77.4];   // RESET
sw_bootsel = [68.6, 83.6];   // RP BOOTSEL (pinhole)
sw_s3_en   = [68.6, 65];   // ESP32-S3 EN (pinhole)
sw_s3_boot = [68.6, 71.2];   // ESP32-S3 BOOT (pinhole)
led_ws     = [120, 37.5];   // WS2812 status LED
led_rp     = [120, 47];   // RP activity LED
usb_c      = [127.4, 35];   // USB-C exits the top edge
microsd    = [109.3, 35];   // microSD exits the top edge
esp32_ant  = [75.7, 35];   // ESP32-S3 antenna centre (at the top edge)
